early_access: false
enable_free_tier: true
language: en
tone_instructions: ''
knowledge_base:
  learnings:
    scope: auto
  issues:
    scope: auto
  jira:
    project_keys: []
  linear:
    team_keys: []
chat:
  auto_reply: true
reviews:
  profile: chill
  request_changes_workflow: false
  high_level_summary: true
  high_level_summary_placeholder: '@coderabbitai summary'
  poem: false
  review_status: true
  collapse_walkthrough: false
  path_filters: []
  path_instructions:
    - path: '**/*.go'
      instructions: >-
        Review the Go code, point out issues relative to idiomatic Go, clean code principles, error handling, concurrency, and performance.
  auto_review:
    enabled: true
    ignore_title_keywords:
      - WIP
    labels: []
