version: 1
disable_existing_loggers: false
formatters:
  detailed:
    format: "[%(asctime)s][%(levelname)s | %(filename)s:%(lineno)s] >>> %(message)s"
    datefmt: "%Y-%m-%d %H:%M:%S:%Z"
  json:
    (): server.utils.core.logging.logger.JSONFormatter
    fmt_keys:
      level: levelname
      message: message
      timestamp: timestamp
      logger: name
      module: module
      function: funcName
      line: lineno
      threadName: threadName
handlers:
  stderr:
    class: logging.StreamHandler
    level: WARNING
    formatter: detailed
    stream: ext://sys.stdout
  file:
    class: logging.handlers.RotatingFileHandler
    level: DEBUG
    formatter: json
    filename: logs/app.log.jsonl
    maxBytes: 10485760
    backupCount: 5
  queue_handler:
    class: logging.handlers.QueueHandler
    handlers:
    - file
    - stderr
    respect_handler_level: true
loggers:
  root:
    level: DEBUG
    handlers:
    - queue_handler
